<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<Version>0.12.0</Version>
	<Title>Neumorphism.Avalonia</Title>
	<Authors>Eviral</Authors>
	<Company>Eviral</Company>
	<PackageDescription>Easy to use and customizable Neumorphism Design implementation for Avalonia UI framework.</PackageDescription>
	<Description>Easy to use and customizable Neumorphism Design implementation for Avalonia UI framework.</Description>
	<PackageProjectUrl>https://github.com/flarive/Neumorphism.Avalonia</PackageProjectUrl>
	<PackageLicenseUrl></PackageLicenseUrl>
  <PackageId>Neumorphism.Avalonia</PackageId>
	<RepositoryUrl>https://github.com/flarive/Neumorphism.Avalonia</RepositoryUrl>
	<PackageIcon>Icon.png</PackageIcon>
	<RepositoryType>git</RepositoryType>
	<LangVersion>9</LangVersion>
	<Nullable>disable</Nullable>
	<PackageReleaseNotes>
		Easy to use and customizable Neumorphism Design implementation for AvaloniaUI framework.
		Demo app can be found here : https://github.com/flarive/Neumorphism.Avalonia
	</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
	  <PackageReference Include="Avalonia" Version="12.0.4" />
	  <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
	  <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.0" />
	  <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0" />
	  <PackageReference Include="ReactiveUI.Avalonia" Version="12.0.3" />
	  <PackageReference Include="DialogHost.Avalonia" Version="0.12.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <AvaloniaResource Include="**/*.xaml" />  
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Fonts\SF\SFProText-Light.ttf" />
    <AvaloniaResource Include="Fonts\SF\SFProText-Medium.ttf" />
    <AvaloniaResource Include="Fonts\SF\SFProText-Regular.ttf" />
    <AvaloniaResource Include="Themes\Ripple.axaml" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Icon.png" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
